- hosts: localhost 
  gather_facts: no #optimization to gather facts only when required
  vars_files:
    - creds.yml
  roles:
    - yugabyte_vpc
    - yugabyte_ec2_sg
    - yugabyte_ec2
 
- hosts: tag_Env_Yugabyte_nodes*
  gather_facts: no 
  pre_tasks:
    - setup:
  roles:
    - yugabyte_common
    - yugabyte_setup
    
- hosts: tag_Env_Yugabyte_nodes_master
  gather_facts:	no
  pre_tasks:
    - setup: # gather facts only when needed not every time
  roles:
    - role: yugabyte_tbserver_startup
      vars:
        file_config: master.conf
        process: yb-master
        basedir_yugabyte: "{{ master_dir }}"
       
- hosts: tag_Env_Yugabyte_nodes*
  gather_facts:	no
  pre_tasks:
    - setup:
  roles:
    - role: yugabyte_tbserver_startup
      vars:
        file_config: "tserver.conf"
        process: yb-tserver
        basedir_yugabyte: "{{ tserver_dir }}"
        
- hosts: tag_Name_Yugabyte_nodes_master_1
  gather_facts:	no
  pre_tasks:
    - setup:
  vars_files:
    - creds.yml
  roles:
    - configure_region_placement

- hosts: localhost
  gather_facts: no
  vars_files:
    - creds.yml
  roles:
    - { role: get_facts_master, tags: [ 'check_master_ui'] }